blog/urls.py
from django.urls import path

from . import views

app_name = '[blog]'


'''
   此处有瑕疵，应当使用正则表达式来严格约束域名，（域名跳转如果遇到符合的就会跳转，比如：如果edit/<article_id>在edit/action之前，输入edit/action域名，
   会优先跳转进edit/<article_id>中,所以要十分注意，所以交换两个顺序。）-
'''
urlpatterns = [
    path('', views.index),
    path('article/<article_id>', views.article_page, name='article_page'),
    path('edit/action', views.edit_action, name="edit_action"),
    path('edit/<article_id>', views.edit_page, name="edit_page"),

]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models


class Article(models.Model):
    # 数据库
    title = models.CharField(max_length=32, default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(auto_now=True, null=True)

    # 使管理页面展示文章题目
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse

from . import models


def index(request):
    articles = models.Article.objects.all()
    return render(request, 'blog/index.html', {'articles': articles})


# 文章页面
def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/article_page.html', {'article': article})


# 编辑页面，如果是添加新文章，则为空；如果是修改已有文章，则加载文章内容
def edit_page(request, article_id):
    if str(article_id) == '0':
        return render(request, 'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})


# 处理编辑提交行为
def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    article_id = request.POST.get('article_id', '0')

    # 创建新的文章
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})

    # 修改原有文章
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
    <h1>{{ article.title }}</h1>
    <br>
    <h3>{{ article.content }}</h3>
    <br><br>
    <a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
        <---当article为空时，页面不会显示出article的内容
            当创建新文章时，使用django模板过滤器，使article为空时传入默认字符串‘0’
        ->
        <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
        <label for="">文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br>
        <label for="">文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <br>
    <input type="submit" value="提交">
</form>


</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:edit_page' 0 %}">新文章</a></h1>
<br>
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}
</body>
</html>